apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name  }}
data:
  unbound.conf: |-
    server:
        directory: "/etc/unbound"
        interface: {{ .Values.bindTo }}
        access-control: {{ .Values.clusterIpv4Cidr }} allow
        access-control: 127.0.0.1/32 allow
        so-reuseport: yes
        do-daemonize: no
        logfile: ""
        use-syslog: no
        auto-trust-anchor-file: "/var/lib/unbound/root.key"
        verbosity: {{ .Values.verbosity }}

    {{- range .Values.forwardZones }}

    forward-zone:
        name: {{ .name | quote }}
        {{- range .hosts }}
        forward-host {{ . }}
        {{- end }}
    {{- end }}
