apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . | quote }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . | quote }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "fullname" . | quote }}
  template:
    metadata:
      labels:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: {{ template "fullname" . | quote }}
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: "unbound"
        image: {{ .Values.image | quote }}
        imagePullPolicy: "IfNewer"
        resources:
          requests:
            memory: {{ .Values.memRequest | quote }}
            cpu: {{ .Values.cpuRequest | quote }}
          limits:
            memory: {{ .Values.memLimit | quote }}
        ports:
        - name: "dns"
          containerPort: 53
          protocol: "UDP"
        volumeMounts:
        - name: "unbound-conf"
          mountPath: "/etc/unbound/"
          readOnly: true
        livenessProbe:
          exec:
            command:
              - "nslookup"
              - "google.com"
              - "127.0.0.1"
          initialDelaySeconds: 10
          timeoutSeconds: 2
        readinessProbe:
          exec:
            command:
              - "nslookup"
              - "google.com"
              - "127.0.0.1"
          initialDelaySeconds: 10
          timeoutSeconds: 2
      volumes:
      - name: "unbound-conf"
        configMap:
          name: {{ template "fullname" . | quote }}
